name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
      - name: Install Packages
          run: yarn
      - name: Install Packages
          run: yarn test:format

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
      - name: Install Packages
          run: yarn
      - name: Install Packages
          run: yarn test:lint

